# Manajemen Bisnis {#Manajemen-Bisnis} 
*** 

Bab ini mencakup beberapa perhitungan matematika yang sering ditemukan dalam manajeman bisnis secara umum, dapat diterapkan diberbagai profesi bisnis seperti halnya Marketing (Pemasaran), Akuntansi, Produksi, Sumber Daya Manusia (HRD), Ekonomi, Keuangan, Analis Bisnis, dll. Dalam hal ini, saya mengasumsikan anda ingin menjadi owner/manajer perusahaan yang sukses, Anda perlu memahami beberapa hal mendasar dalam matematika bisnis seperti;

## Rata-rata

Rata-rata nilai (besaran) yang diperoleh dari hasil jumlah tiap data dibagi dengan banyaknya data, nilai tersebut secara lumrah digunakan menjadi acuan untuk mewakili sekumpulan data. Pada saatnya nanti, ketika anda bekerja disuatu perusahaan, Manajer atau anda sendiri akan seringkali mempertanyakan, "Berapa rata-rata penjualan perusahaan kita setiap Tahun,bulan, minggu, bahkan hingga harian".  

Perlu diketahui bahwa nilai rata-rata biasanya digunakan untuk mengevaluasi data sehingga lebih cepat dan menggambarkan seluruh data serta tidak dapat digunakan untuk menentukan nilai data tertentu di antara sekelompok data, sebagai contoh misalnya nilai rata-rata budi yaitu 85 jadi tidak bisa disimpulkan bahwa nilai untuk pelajaran Matematika Budi lebih dari 75. Nilai rata-rata tersebut bisa dipakai untuk membandingkan kelompok data yang satu dengan yang lainnya, seperti yg nilai rata-rata kelas yaitu 85 sedangkan nilai rata-rata kelas B yaitu 87 itu berarti kelas B lebih tinggi daripada kelas A.

Berikut rumus cara menghitung nilai rata-rata pada suatu kelompok,

$$ \small{ \text{Nilai Rata-rata}= {\text{Jumlah Nilai} \over \text{Banyak Data}} }$$

Berikut ini data nilai tes kuliah Matematika Bisnis 10 mahasiswa/i, kita akan menghitung nilai rata-rata yang diperoleh.

No     Nama                          Nilai
---   ---------------------         --------------------------
1	     Eka Baper Sendiri	               85
2	     Putri Woles Aja	                 78
3	     Bagus Sipemuja Mantan 	           90
4	     Neneng Gadis Desa                 75
5	     Adi Korban Pelakor	               92
6	     Bintang Bete                      85
7	     Toni Raja Kepo                    85
8	     Rina Capedeh     	               82
9	     Romy Kuper Abis                   96
10	   Andika Pehape        	           90

$$
\small{
\begin{aligned}
\text{Jumlah nilai} &= 85 + 78 + 90 + 75 + 92 + 85 + 85 + 82 + 96 + 90 = 858 \\
\text{Jumlah data} & = 10\\
\text{Nilai rata-rata} & = 858/10 = 85,8
\end{aligned}
}
$$

Jadi nilai rata-rata pelajaran Matematika 10 siswa tersebut adalah 85,8.

### Nilai Rata-Rata dengan Penambahan Data

Apabila ada tambahan data maka jumlah nilai serta banyaknya data menjadi berubah. Jika ada penambahan satu data dengan nilai $a$ maka,

$$
\small{
\begin{aligned}
\text{Jumlah nilai sekarang} &= \text{Jumlah nilai} + a \\ 
\text{Banyaknya data sekarang} & = \text{Banyaknya data} + 1 
\end{aligned}
}
$$

Contoh lainnya, misalkan ada penambahan dua data dengan nilai $a_1$ dan $a_2$ maka

$$
\small{
\begin{aligned}
\text{Jumlah nilai sekarang} & = \text{Jumlah nilai} + (a_1 + a_2) \\ 
\text{Banyaknya data sekarang} & = \text{Banyaknya data} + 2
\end{aligned}
}
$$

Sebagai contoh misalnya jika diketahui nilai rata-rata dari sekelompok data ditambah data tambahan. Misal diketahui nilai rata-rata tes mata pelajaran Bahasa Indonesia dari 8 orang Mahasiswa/i adalah 86.

Dua orang Mahasiswa/i tidak hadir saat tes dan mengikuti tes susulan, masing masing mendapat nilai 100 dan 87. Kita akan menghitung nilai rata-rata dari 10 orang Mahasiswa/i tersebut.

$$
\small{
\begin{aligned}
\text{Nilai rata-rata} & = \text{Jumlah nilai/banyaknya data} \\
\text{Jumlah nilai} & = \text{(Nilai rata-rata)} \times \text{(Banyaknya data)} \\
\text{Jumlah nilai} & = 86 \times 8 = 688 \\
\text{Jumlah nilai sekarang} & = 688 + 100 + 87 = 875 \\
\text{Banyaknya data sekarang} & = 8 + 2 = 10 \\
\text{Nilai rata-rata sekarang} &= 875 / 10 = 87,5
\end{aligned}
}
$$

Jadi nilai rata-rata pelajaran Bahasa Indonesia 10 Mahasiswa/i tersebut adalah 87,5.

### Nilai Rata-Rata dengan Pengurangan Data

Jika ada pengurangan data maka jumlah nilai dan banyaknya data menjadi berubah. Jika ada pengurangan satu data dengan nilai $a$ maka,

$$
\small{
\begin{aligned}
\text{Jumlah nilai sekarang}  & = \text{Jumlah nilai} – a\\
\text{Banyaknya data sekarang}& = \text{Banyaknya data} – 1
\end{aligned}
}
$$

Contoh lain, misalkan ada penguragan tiga data dengan nilai $a_1 , a_2$ dan $a_3$ maka,

$$
\small{
\begin{aligned}
\text{Jumlah nilai sekarang} &= \text{Jumlah nilai} – (a_1 + a_2 + a_3) \\
\text{Banyaknya data sekarang}& = \text{Banyaknya data} – 3
\end{aligned}
}
$$


## Rasio

Rasio adalah suatu angka yang dibandingkan dengan angka lain sebagai suatu hubungan. Menurut Jonathan Golin, berpendapat bahwa rasio adalah suatu angka digambarkan dalam suatu pola yang dibandingkan dengan pola lainnya serta dinyatakan dalam persentase. Sedangkan keuangan adalah sesuatu yang berhubungan dengan akuntansi seperti pengelolaan keuangan dan laporan keuangan. Analisis rasio keuangan digunakan oleh dua pengguna utama, yakni investor dan manajemen. Investor menggunakan analisis rasio untuk melihat apakah perusahaan itu investasi yang bagus atau tidak.  

Analisis Rasio Keuangan atau Financial Ratio adalah merupakan suatu alat analisis yang digunakan oleh perusahaan untuk menilai kinerja keuangan berdasarkan data perbandingan masing-masing pos yang terdapat di laporan keuangan seperti Laporan Neraca, Rugi /Laba, dan Arus Kas dalam periode tertentu.

### Fungsi Analisis Rasio

* Rasio Likuiditas (Liquidity Ratio): Rasio likuiditas adalah rasio yang mengukur kemampuan likuiditas jangka pendek suatu perusahaan dengan melihat aktiva lancar perusahaan relatif terhadap hutang lancarnya.
* Rasio Perputaran Persediaan (Inventory turnover ratio): Rasio perputaran persediaan mengukur aktivitas atau likuiditas perusahaan dilihat dari ketersediaan barang. Rasio ini menunjukkan efisiensi di mana perusahaan menggunakan seluruh aktivanya untuk menghasilkan penjualan.
* Rasio Aktivitas (Activity Ratio): Rasio aktivitas menunjukkan tingkat efektivitas penggunaan aktiva atau kekayaan perusahaan kepada Anda.
* Rasio Profitabilitas dan Rentabilitas (Profitability Ratio): Merupakan rasio yang menunjukkan tingkat imbalan atau perolehan dibanding penjualan atau aktiva.
* Rasio Investasi (Investment Ratio): Rasio investasi merupakan rasio yang mengukur kemampuan perusahaan dalam memberikan kembalian atau imbalan kepada para pemberi dana, khususnya investor yang ada di pasar modal dalam jangka waktu tertentu.

### Tujuan Analisis Rasio

* Sebagai alat barometer untuk melakukan forecasting atau memproyeksikan posisi keuangan dimasa yang akan datang.
* Meninjau kondisi perusahaan saat ini, permasalahan dalam manajemen, operasional maupun, keuangan.
* Alat ukur untuk melakukan efisiensi di semua departemen perusahaan.


## Persen Perubahan

Dalam matematika, persentase perubahan digunakan untuk menunjukkan selisih atau perbedaan antara **nilai sebelum** dan **nilai sesudah** dalam bentuk persen nilai sebelum. Berikut adalah beberapa teknik yang digunakan untuk menganalisis persentasi perubahan yang sering ditemukan dalam laporan kinerja, perhitungan dalam keuangan, evaluasi laba atau rugi, dan juga sering digunakan untuk menganalisa kompetitor suatu perusahaan.

### Analisis Tren

Analisa tren juga disebut analisis time-series. Analisis tren membantu manajer keuangan perusahaan menentukan bagaimana perusahaan cenderung melakukan kinerja dari waktu ke waktu. Analisis tren didasarkan pada data historis dari laporan keuangan perusahaan dan data perkiraan dari  performa atau rencana ke depan perusahaan.

Salah satu cara yang populer dalam melakukan analisis tren adalah dengan menggunakan analisis rasio keuangan. Jika Anda menghitung rasio keuangan untuk perusahaan bisnis, Anda harus menghitung rasio minimal dua tahun terakhir, karena perbandingan rasio tidak berarti kecuali Anda memiliki sesuatu untuk membandingkannya dengan data tahun yang lain. Analisis tren akan lebih bagus lagi jika Anda memiliki dan menggunakan data rasio keuangan lebih dari 2 tahun.

### Analisis Common Size

Analisis laporan keuangan common size menganalisis neraca dan laporan laba rugi dengan menggunakan persentase. Dalam analisis common size, semua akun laporan laba rugi dinyatakan sebagai persentase penjualan. Semua akun neraca dinyatakan sebagai persentase dari total aset. Misalnya, jika pada laporan laba rugi, setiap akun baris dibagi dengan penjualan, maka di neraca, setiap akun baris dibagi dengan total aset. Jenis analisis ini memungkinkan manajer keuangan untuk melihat laporan laba rugi dan neraca dalam format persentase yang mudah ditafsirkan, karena lebih mudah membuat perbandingan menggunakan persentase daripada angka absolut.

### Analisis Persentase Perubahan

Analisis laporan keuangan ini sedikit lebih rumit. Bila menggunakan bentuk analisis ini, Anda harus menghitung tingkat pertumbuhan untuk semua akun laporan laba rugi dan akun neraca relatif terhadap tahun dasar. Teknik Ini adalah bentuk analisis laporan keuangan yang sangat kuat. Dengan teknik ini, Anda dapat melihat bagaimana berbagai akun laporan laba rugi dan akun neraca tumbuh atau relatif menurun terhadap pertumbuhan atau penurunan penjualan dan total aset.

### Analisis Kempetitor

Analisis ini melibatkan perbandingan perusahaan dengan perusahaan lain di industri yang sama untuk melihat bagaimana perusahaan melakukan investasi secara finansial dibandingkan dengan industri lainnya. Jenis analisis ini sangat membantu manajer keuangan untuk melihat apakah ada penyesuaian finansial yang perlu dilakukan.

Teknik penghitungan rasio keuangan biasanya digunakan untuk analisis ini. Untuk melakukan pembandingan, Anda membutuhkan rasio rata-rata dari perusahaan lain di industri yang sama untuk dibandingkan dengan rasio bisnis Anda. Dengan teknik ini, Anda harus yakin bahwa rasio rata-rata industri lain tersebut telah dihitung dengan cara yang sama dengan rasio untuk perusahaan yang dihitung saat Anda melakukan analisis industri ini. Dengan menggunakan keempat teknik analisis laporan keuangan ini, seorang manajer keuangan akan mengetahui di mana potensi bisnis perusahaan baik secara finansial maupun internal berada, dibandingkan dengan perusahaan lain di industri yang sama.


## Proporsi

Proporsi adalah pecahan yang pembilangnya merupakan bagian dari penyebutnya. Dengan kata lain persentase proporsi menghitung persentase dari sebuah variabel dengan membandingkan variabel tersebut dengan pembandingnya yang mana varibale tersebut merupakan bagian dari variable pembanding tersebut. Contohnya kasusnya begini: Pada acara pembukaan suatu Mall baru Jakarta, dilakukan pengumpulan data 2000 pengunnjung. Dari 2000 pengunjung tersebut 200 pengunjung ternyata adalah laki-laki dan sisanya  adalah perempuan.

* Berapakah persentase pengunjung laki-laki dari seluruh pengunjung yang ada?
* Berapakah persentase pengunjung perempuan dari seluruh pengunjung yang ada?

Untuk menghitung persentase tersebut mengikuti rumus matematika berikut:

$$ \% \text{ Proporsi}  = {\text{Nilai Proporsi} \over \text{Pembanding Proporsi}} \times 100 \%$$

## Prorata

Pro rata adalah istilah Latin yang berarti “dalam proporsi,” mengacu pada alokasi proporsional atau distribusi atas sesuatu. 

### Memahami Prorata

Pro rata mengacu pada pembagian yang sama atas sesuatu – termasuk suku bunga, pengeluaran, keuntungan pemegang saham (dividen), atau jumlah lain yang dibagi antara beberapa orang atau dalam kurun waktu tertentu. Istilah ini bisa digunakan di bidang apa saja, tetapi lebih sering muncul di bidang keuangan. Untuk menghitung bagian prorata, bagilah totalnya dengan jumlah unit yang ditentukan. Prorata sering digunakan secara bergantian dengan “pembagian secara proporsional.”

### Contoh Kasus Prorata

Katakanlah Perusahaan Ritel fiksi mengumumkan bahwa, pada kuartal keempat tahun ini, ia akan membayar dividen senilai Rp1 Miliar kepada pemegang saham. Setiap saham akan bernilai prorata, yang berarti jumlah proporsional dari dividen yang dibayarkan. Jika ada 500 saham yang beredar, jumlah prorata setiap saham bernilai Rp2,000,000 (Rp1 Miliar dibagi 500 saham). 

Pro rata sering muncul dalam berbagai bidang, baik di bidang keuangan dan kehidupan sehari-hari. Istilah ini sering digunakan secara bergantian dengan “pembagian secara proporsional,” yang juga mengacu pada distribusi proporsional atas sesuatu, baik itu dividen, upah, atau suku bunga.Menetapkan pro rata hanya masalah membagi jumlah total sesuatu dengan jumlah bagian. Sebagai contoh sederhana, jika kamu memiliki total 100 unit sesuatu untuk dibagi menjadi 5 bagian yang sama, masing-masing bagian prorata adalah 20 unit (100 unit ÷ 5 bagian = 20 unit per bagian).

### Kesimpulan Prorata

Seperti halnya membagi kue, jika anda mempunyai satu kue dan berencana membagikannya dengan lima temanmu, maka anda harus membagi kue menjadi enam. Bagian pro rata pencuci mulut setiap orang sama dengan seperenam kue.

### Penerapan Prorata

Berikut adalah contoh beberapa hal di mana prorata sering muncul:

#### a. Dividen Pemegang Saham (Shareholder Dividends){-}

Dalam dunia keuangan, pro rata sering digunakan untuk menentukan jumlah dividen yang akan diterima oleh pemegang saham. Ketika perusahaan telah membayar dividen, setiap pemegang saham akan menerima jumlah yang proporsional dengan persentase saham yang mereka miliki.Katakanlah ada total 500 saham di perusahaan, dan perusahaan membayar dividen senilai Rp500 juta. Dengan membagi jumlah total uang dan jumlah saham, bisa dipastikan bahwa setiap saham akan menghasilkan Rp1 juta dividen untukmu. 

#### b. Usaha Bersama (Joint Ventures){-}

Pro rata berperan penting dalam usaha bersama (ketika dua orang atau lebih memulai bisnis bersama). Usaha bersama termasuk perseroan terbatas, perusahaan, dan kemitraan. Seorang pemilik perusahaan menentukan bagiannya dari biaya dan laba. Berikut adalah contoh bagaimana prorata akan berperan dalam kasus kemitraan:

* **Tanggung Jawab:** Tingkat tanggung jawab mitra (biaya yang menjadi tanggung jawab mitra) dalam suatu bisnis ditentukan berdasarkan prorata yang sesuai dengan sahamnya di perusahaan. Katakanlah suatu kemitraan dituntut senilai Rp100 juta dan kalah. Mitra A memiliki 60% saham di perusahaan, sementara Mitra B memiliki 40%. Masing-masing tanggung jawab mitra sesuai dengan bagiannya di perusahaan. Mitra A bertanggungjawab atas 60% dari utang (dalam hal ini, Rp60 juta), dan Mitra B bertanggungjawab atas 40% (atau Rp40 juta).
* **Keuntungan:** Sama halnya dengan tanggung jawab, bagian keuntungan pro rata  dalam suatu kemitraan didasarkan pada bunga yang diperoleh perusahaan. Jika keuntungan dalam perusahaan yang sama mencapai Rp100 juta, Mitra A mendapat Rp60 juta dan Mitra B mendapat Rp40 juta.

#### c. Suku Bunga (Interest Rates){-}

Pro rata bisa digunakan untuk membagi suku bunga menjadi bagian yang lebih kecil – seringkali tarif tahunan menjadi tarif bulanan. Misalnya, jika suku bunga tahunan dalam pinjaman adalah 12%, tingkat bulanannya adalah 1% (12% ÷ 12 bulan).

#### d. Surat Perjanjian Asuransi (Insurance Policies){-}

Prorata ikut berperan ketika kamu membatalkan surat perjanjian asuransi lebih awal. Jika kamu membayar Rp6 juta untuk asuransi selama enam bulan dan dibatalkan setelah tiga bulan, perusahaan asuransi akan mengembalikan jumlah yang setara. Dalam hal ini, karena kamu membatalkan kebijakan, kamu akan memenuhi syarat utuk pengembalian uang senilai 50%. Pro rata juga digunakan untuk menentukan pembayaran bulanan kamu. Seringkali perusahaan asuransi menetapkan harga suatu kebijakan selama periode enam atau 12 bulan, tetapi banyak pelanggan yang tidak mau membayar bunga mereka sekaligus. Sebaliknya, perusahaan asuransi membagikan bunga sehingga pelanggan membayar jumlah yang ditentukan setiap bulan.                                                 

#### e. Pembayaran Pinjaman (Loan Payments){-}

Contoh pro rata lainnya adalah bagian pinjaman menjadi pembayaran bulanan. Saat kamu mengambil pinjaman – baik itu pinjaman pribadi, pinjaman mobil, atau hipotek – saldo dibagi selama masa pinjaman. Dalam gabungan bunga, adalah bagaimana pemberi pinjaman menentukan seperti apa cara pembayaran bulanannya.

#### f. Apartemen {-}

Pro rata sering muncul dalam penyewaan apartemen. Umumnya, sewa dikenakan biaya bulanan, tetapi bagaimana jika kamu tidak tinggal di apartemen selama sebulan penuh? Mungkin kamu mulai menyewa beberapa hari dalam sebulan atau berakhir di pertengahan bulan.Dalam hal ini, pemilik apartemen mungkin akan membuat prorata sewa kamu, atau hanya menagih berdasarkan jumlah hari yang kamu habiskan di apartemen. Sebagai contoh, katakanlah sewa bulanan kamu adalah Rp5 juta, dan kamu mulai menyewa pada 3 September. Pemilik apartemen akan menghitung jumlah pro rata yang kamu miliki dengan menentukan biaya sewa harian dan mengalikannya dengan jumlah hari kamu saat berada di Apartemen.Sejak September ada 30 hari, pemilik akan membagi Rp5 juta dengan 30 untuk menentukan tarif harian, hasilnya adalah Rp166 ribu. Kemudian, dia akan mengalikan tarif harian dengan jumlah hari yang dihabiskan di apartemen, atau Rp166 x 28 hari. Jadi, total biaya akhir Rp4,648,000.


#### g. Gaji Pro Rata{-}

Salah satu kegunaan pro rata pada umumnya berlaku untuk karyawan yang memiliki gaji. Umumnya, gaji adalah upah yang dinyatakan sebagai jumlah tahunan, bukan gaji per jam. Gaji biasanya mengasumsikan karyawan yang bekerja tahunan dengan jumlah minimum jam per minggu (biasanya 40).Jika kamu seorang karyawan yang mendapatkan gaji tahunan, prorata digunakan untuk menentukan berapa banyak gaji yang kamu dapatkan. Misalnya, katakanlah kamu mendapatkan gaji tahunan Rp120 juta dan dibayar setiap dua minggu. Kamu akan digaji 26 kali dalam setahun, sehingga pemberi kerja akan menjumlah gaji dan dibagi 26 untuk menentukan berapa yang harus dibayarkan padamu setiap dua minggu. Hasil gaji selama dua minggu adalah Rp4,615,000.


## Latihan 

Untuk memastikan anda memahami materi dengan baik, berikut ini diberikan latihan yang mencakup pembahasan diatas secara praktikal dalam Excel. Silahkan download file latihan [disini](https://github.com/Bakti-Siregar/Matematika-Bisnis/blob/master/data/matematika-manajemen-bisnis.xlsx?raw=true).






